# Generated by Django 4.1.3 on 2022-11-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_location_user_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'участник'), ('moderator', 'модератор'), ('admin', 'администратор')], default='member', max_length=9),
        ),
    ]
